In [3]:
%pip install pandas
import pandas as pd

train = pd.read_csv(
    "../data/raw/goemotions/train.tsv",
    sep="\t"
)

train.head()

Requirement already satisfied: pandas in /Users/reesha/rl-env/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in /Users/reesha/rl-env/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/reesha/rl-env/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/reesha/rl-env/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

  My favourite food is anything I didn't have to cook myself.  27  eebbqej
0  Now if he does off himself, everyone will thin...           27  ed00q6i
1                     WHY THE FUCK IS BAYLESS ISOING            2  eezlygj
2                        To make her feel threatened           14  ed7ypvh
3                             Dirty Southern Wankers            3  ed0bdzj
4  OmG pEyToN iSn'T gOoD eNoUgH tO hElP uS iN tHe...           26  edvnz26

In [4]:
print(train.columns)
print(train.shape)

Index(['My favourite food is anything I didn't have to cook myself.', '27',
       'eebbqej'],
      dtype='str')
(43409, 3)

In [5]:
dair = pd.read_csv(
    "../data/raw/dair_emotion/train.csv"
)

print(dair.columns)
print(dair.shape)

Index(['text', 'label'], dtype='str')
(16000, 2)

In [6]:
import pandas as pd

train = pd.read_csv("../data/raw/goemotions/train.tsv", sep="\t")

print(train.columns)
print(train.head())
print(train.shape)

Index(['My favourite food is anything I didn't have to cook myself.', '27',
       'eebbqej'],
      dtype='str')
  My favourite food is anything I didn't have to cook myself.  27  eebbqej
0  Now if he does off himself, everyone will thin...           27  ed00q6i
1                     WHY THE FUCK IS BAYLESS ISOING            2  eezlygj
2                        To make her feel threatened           14  ed7ypvh
3                             Dirty Southern Wankers            3  ed0bdzj
4  OmG pEyToN iSn'T gOoD eNoUgH tO hElP uS iN tHe...           26  edvnz26
(43409, 3)

In [7]:
import pandas as pd

train = pd.read_csv(
    "../data/raw/goemotions/train.tsv",
    sep="\t",
    header=None,
    names=["text", "label", "id"]
)

print(train.head())
print(train.columns)
print(train.shape)

                                                text label       id
0  My favourite food is anything I didn't have to...    27  eebbqej
1  Now if he does off himself, everyone will thin...    27  ed00q6i
2                     WHY THE FUCK IS BAYLESS ISOING     2  eezlygj
3                        To make her feel threatened    14  ed7ypvh
4                             Dirty Southern Wankers     3  ed0bdzj
Index(['text', 'label', 'id'], dtype='str')
(43410, 3)

In [8]:
import pandas as pd

stats = {
    "samples": len(train),
    "unique_labels": train["label"].nunique(),
    "avg_text_length": train["text"].str.len().mean(),
    "max_text_length": train["text"].str.len().max(),
    "min_text_length": train["text"].str.len().min()
}

stats_df = pd.DataFrame([stats])

stats_df.to_csv(
    "../data/metadata/goemotions_stats.csv",
    index=False
)

stats_df

   samples  unique_labels  avg_text_length  max_text_length  min_text_length
0    43410            711        68.400875              703                2

In [9]:
dair = pd.read_csv(
    "../data/raw/dair_emotion/train.csv"
)

stats = {
    "samples": len(dair),
    "unique_labels": dair["label"].nunique(),
    "avg_text_length": dair["text"].str.len().mean(),
    "max_text_length": dair["text"].str.len().max(),
    "min_text_length": dair["text"].str.len().min()
}

pd.DataFrame([stats]).to_csv(
    "../data/metadata/dair_stats.csv",
    index=False
)